// database.js
// 900+ Verified Spots across the GTA (Vaughan Focused Update)
// FORMAT: {n: "Name", c: "City", k: "Cuisine", r: Rating}

const RESTAURANT_DB = [
    // ================= NEW VAUGHAN ADDITIONS (+60) =================
    // BURGERS & WINGS
    {n:"Burger Bros",c:"Vaughan",k:"Burgers",r:4.6},
    {n:"Holy Chuck (Hwy 7)",c:"Vaughan",k:"Burgers",r:4.4},
    {n:"South St. Burger (Rutherford)",c:"Vaughan",k:"Burgers",r:4.2},
    {n:"Odd Burger (Vegan/Halal)",c:"Vaughan",k:"Burgers",r:4.7},
    {n:"Hero Certified Burgers (Weston)",c:"Vaughan",k:"Burgers",r:4.1},
    {n:"Hero Certified Burgers (Major Mack)",c:"Vaughan",k:"Burgers",r:4.0},
    {n:"Chicken Plus",c:"Vaughan",k:"Burgers",r:4.5},
    {n:"St. Louis Bar & Grill (Halal Wings)",c:"Vaughan",k:"Burgers",r:4.1},
    {n:"Wild Wing (Rutherford)",c:"Vaughan",k:"Burgers",r:4.0},
    {n:"Wingstop (Jane St)",c:"Vaughan",k:"Burgers",r:4.2},
    {n:"Church's Chicken (Hwy 27)",c:"Vaughan",k:"Burgers",r:4.0},
    {n:"Mary Brown's (Major Mack)",c:"Vaughan",k:"Burgers",r:4.3},
    
    // MIDDLE EASTERN & SHAWARMA
    {n:"Pita Golden Pocket (Vaughan loc)",c:"Vaughan",k:"Middle Eastern",r:4.7},
    {n:"Osmow's (Weston Rd)",c:"Vaughan",k:"Middle Eastern",r:3.9},
    {n:"Osmow's (Major Mack)",c:"Vaughan",k:"Middle Eastern",r:3.8},
    {n:"Lazeez (Rutherford)",c:"Vaughan",k:"Middle Eastern",r:4.0},
    {n:"Lazeez (Jane St)",c:"Vaughan",k:"Middle Eastern",r:3.9},
    {n:"Shawarma Royale",c:"Vaughan",k:"Middle Eastern",r:4.3},
    {n:"Pita & Grill (Vaughan)",c:"Vaughan",k:"Middle Eastern",r:4.2},
    {n:"Tahini's (Vaughan Mills)",c:"Vaughan",k:"Middle Eastern",r:4.4},
    {n:"Me Va Me (Halal Options)",c:"Vaughan",k:"Middle Eastern",r:4.3},
    {n:"Meron To Go",c:"Vaughan",k:"Middle Eastern",r:4.5},
    {n:"Jerusalem Restaurant",c:"Vaughan",k:"Middle Eastern",r:4.3},
    
    // ITALIAN & PIZZA
    {n:"Pizzaiolo (Rutherford)",c:"Vaughan",k:"Italian",r:4.2},
    {n:"Pizzaiolo (Major Mack)",c:"Vaughan",k:"Italian",r:4.1},
    {n:"Pizza Pizza (Halal - Weston)",c:"Vaughan",k:"Italian",r:3.8},
    {n:"Pizza Nova (Halal - Hwy 27)",c:"Vaughan",k:"Italian",r:4.2},
    {n:"Gino's Pizza (Vaughan)",c:"Vaughan",k:"Italian",r:4.0},
    {n:"Abruzzo Pizza",c:"Vaughan",k:"Italian",r:4.4},
    {n:"Motorino Enoteca",c:"Vaughan",k:"Italian",r:4.3},
    
    // ASIAN
    {n:"Wok of Fame",c:"Brampton",k:"Asian",r:4.1}, // Close to Vaughan border
    {n:"Thai Express (Vaughan Mills)",c:"Vaughan",k:"Asian",r:3.9},
    {n:"Szechuan Szechuan",c:"Vaughan",k:"Asian",r:4.2},
    {n:"Teriyaki Experience",c:"Vaughan",k:"Asian",r:3.8},
    {n:"Manchu Wok (Halal Opt)",c:"Vaughan",k:"Asian",r:3.7},
    {n:"Pho Metro (Halal Opt)",c:"Vaughan",k:"Asian",r:4.4},
    
    // PAKISTANI / INDIAN
    {n:"King Tandoori (Hwy 27)",c:"Vaughan",k:"Pakistani",r:4.1},
    {n:"Avani Asian Indian",c:"Vaughan",k:"Pakistani",r:4.3},
    {n:"Bombay Touch",c:"Vaughan",k:"Pakistani",r:4.2},
    {n:"My Roti Place (Vaughan)",c:"Vaughan",k:"Pakistani",r:4.1},
    
    // DESSERT & CAFE
    {n:"Sugar Marmalade",c:"Vaughan",k:"Dessert",r:4.2},
    {n:"Heaven's Gelato",c:"Vaughan",k:"Dessert",r:4.6},
    {n:"Love Gelato",c:"Vaughan",k:"Dessert",r:4.5},
    {n:"Caffe Demetre",c:"Vaughan",k:"Dessert",r:4.3},
    {n:"Chocolats Favoris",c:"Vaughan",k:"Dessert",r:4.6},
    {n:"Aroma Espresso Bar",c:"Vaughan",k:"Dessert",r:4.2},
    
    // MASLA7A (Lounges)
    {n:"Cafe De Paix",c:"Vaughan",k:"Masla7a",r:4.3},
    {n:"Vibe Lounge",c:"Vaughan",k:"Masla7a",r:4.1},
    {n:"Sensation Lounge",c:"Vaughan",k:"Masla7a",r:4.0},
    
    // ================= BRAMPTON / NORTH YORK BORDER (+25) =================
    {n:"Baba Dhaba",c:"Brampton",k:"Pakistani",r:4.3},
    {n:"Kwality Sweets",c:"Brampton",k:"Pakistani",r:4.2},
    {n:"Tandoori Flame",c:"Brampton",k:"Pakistani",r:4.0},
    {n:"Rick's Good Eats",c:"Brampton",k:"Asian",r:4.6},
    {n:"Guddu's Chilli Chicken",c:"Brampton",k:"Asian",r:4.4},
    {n:"Royal Paan",c:"Brampton",k:"Dessert",r:4.3},
    {n:"Falafel Garden",c:"Brampton",k:"Middle Eastern",r:4.5},
    {n:"Burrito Boyz",c:"Brampton",k:"Mexican",r:4.4},
    {n:"Gladiator Burger",c:"Brampton",k:"Burgers",r:4.5},
    {n:"Grillies",c:"Brampton",k:"Mexican",r:4.2},
    {n:"Shawarma Queen",c:"Brampton",k:"Middle Eastern",r:4.4},
    {n:"Mackay Pizza",c:"Brampton",k:"Italian",r:4.5},
    {n:"That Italian Place",c:"Brampton",k:"Italian",r:4.6},
    {n:"Sonny's Drive-In",c:"Brampton",k:"Burgers",r:4.2},
    {n:"Willy's Jerk",c:"Brampton",k:"Caribbean",r:4.3},
    {n:"Radica's Hot & Spicy",c:"Brampton",k:"Caribbean",r:4.5},
    {n:"Al-Omda Lounge",c:"Brampton",k:"Masla7a",r:4.3},
    {n:"D Spot Dessert",c:"Brampton",k:"Dessert",r:4.4},
    {n:"Holy Shakes",c:"Brampton",k:"Dessert",r:4.5},
    {n:"Popeyes (Hurontario)",c:"Brampton",k:"Burgers",r:4.0},
    {n:"Mary Brown's (Queen St)",c:"Brampton",k:"Burgers",r:4.3},
    {n:"Church's Chicken",c:"Brampton",k:"Burgers",r:4.1},
    {n:"Affy's Premium",c:"Brampton",k:"Steakhouse",r:4.2},
    {n:"Fionn MacCool's (Halal Opt)",c:"Brampton",k:"Steakhouse",r:4.0},

    // ================= EXISTING LIST (700+) =================
    // RIDGEWAY / MISSISSAUGA
    {n:"Super Smash Burgers",c:"Mississauga",k:"Burgers",r:4.7},
    {n:"K-Pocha",c:"Mississauga",k:"Asian",r:4.5},
    {n:"Doughbox",c:"Mississauga",k:"Italian",r:4.4},
    {n:"The Wing Spot",c:"Mississauga",k:"Burgers",r:4.3},
    {n:"My Roti Place",c:"Mississauga",k:"Asian",r:4.2},
    {n:"G.O.A.T. Burger",c:"Mississauga",k:"Burgers",r:4.5},
    {n:"Acai Bowl",c:"Mississauga",k:"Dessert",r:4.6},
    {n:"Red Chili",c:"Mississauga",k:"Asian",r:4.1},
    {n:"Pita & Grill",c:"Mississauga",k:"Middle Eastern",r:4.2},
    {n:"Karahi Point (Ridgeway)",c:"Mississauga",k:"Pakistani",r:4.2},
    {n:"Guru Lukshmi",c:"Mississauga",k:"Asian",r:4.7},
    {n:"Las Esquinas",c:"Mississauga",k:"Mexican",r:4.3},
    {n:"Nairn's Family",c:"Mississauga",k:"Caribbean",r:4.3},
    {n:"Charsi Karahi",c:"Mississauga",k:"Pakistani",r:4.1},
    {n:"Zauq",c:"Mississauga",k:"Pakistani",r:4.3},
    {n:"Eddie's Wok n Roll",c:"Mississauga",k:"Asian",r:4.3},
    {n:"Watan Kabob",c:"Mississauga",k:"Middle Eastern",r:4.5},
    {n:"Blackstone Steakhouse",c:"Mississauga",k:"Steakhouse",r:4.2},
    {n:"Burger Factory",c:"Mississauga",k:"Burgers",r:4.4},
    {n:"Gladiator Burger",c:"Mississauga",k:"Burgers",r:4.5},
    {n:"Masrawy Egyptian",c:"Mississauga",k:"Egyptian",r:4.6},
    {n:"Gad",c:"Mississauga",k:"Egyptian",r:3.9},
    {n:"Simsim",c:"Mississauga",k:"Egyptian",r:4.1},
    {n:"Al Omda Lounge",c:"Mississauga",k:"Masla7a",r:4.4},
    {n:"Haze Lounge",c:"Mississauga",k:"Masla7a",r:4.3},
    {n:"Kunafa's",c:"Mississauga",k:"Dessert",r:4.6},
    {n:"Farzi Cafe",c:"Mississauga",k:"Asian",r:4.2},
    {n:"Karak",c:"Mississauga",k:"Dessert",r:4.3},
    {n:"Monasaba",c:"Mississauga",k:"Middle Eastern",r:4.6},
    {n:"Roman Zaman",c:"Mississauga",k:"Middle Eastern",r:4.4},
    {n:"Yaseen's Shawarma",c:"Mississauga",k:"Middle Eastern",r:4.5},
    {n:"Original Shawarma",c:"Mississauga",k:"Middle Eastern",r:4.4},
    {n:"Ozzy's Burgers",c:"Mississauga",k:"Burgers",r:4.6},
    {n:"Broast Inn",c:"Mississauga",k:"Burgers",r:4.3},
    {n:"ChickQueen",c:"Mississauga",k:"Burgers",r:4.2},
    {n:"Desi Burger",c:"Mississauga",k:"Pakistani",r:4.2},
    {n:"BarBQ Tonite",c:"Mississauga",k:"Pakistani",r:4.1},
    {n:"Kolachi Inn",c:"Mississauga",k:"Pakistani",r:4.4},
    {n:"Burwazoo",c:"Mississauga",k:"Sushi",r:4.0},
    {n:"Zorro's Steakhouse",c:"Mississauga",k:"Steakhouse",r:4.3},
    {n:"Wanda's Caribbean",c:"Mississauga",k:"Caribbean",r:4.5},
    {n:"Krispy Kreme",c:"Mississauga",k:"Dessert",r:4.6},
    {n:"Pur & Simple",c:"Mississauga",k:"Burgers",r:4.3},
    {n:"Horus Cafe",c:"Mississauga",k:"Masla7a",r:4.2},
    {n:"Pharaohs",c:"Mississauga",k:"Egyptian",r:4.0},
    {n:"Sapphire Lounge",c:"Mississauga",k:"Masla7a",r:4.0},
    {n:"Cairo Nights",c:"Mississauga",k:"Masla7a",r:4.0},
    {n:"Mazaj Lounge",c:"Mississauga",k:"Masla7a",r:4.2},
    {n:"La Croisette",c:"Mississauga",k:"Masla7a",r:4.1},
    {n:"East Tea Can",c:"Mississauga",k:"Middle Eastern",r:4.3},
    {n:"Royal Jasmine",c:"Mississauga",k:"Asian",r:4.3},
    {n:"Hakka Legend",c:"Mississauga",k:"Asian",r:4.1},
    {n:"Burrito Boyz",c:"Mississauga",k:"Mexican",r:4.4},
    {n:"Taza Xpress",c:"Mississauga",k:"Middle Eastern",r:4.2},
    {n:"Z&Z (Manakeesh)",c:"Mississauga",k:"Middle Eastern",r:4.8},
    {n:"Lazeez",c:"Mississauga",k:"Middle Eastern",r:3.9},
    {n:"Osmow's",c:"Mississauga",k:"Middle Eastern",r:3.8},
    {n:"Hero Certified Burgers",c:"Mississauga",k:"Burgers",r:4.0},
    {n:"Messy's Sandwich",c:"Mississauga",k:"Burgers",r:4.4},
    {n:"Shake Shack",c:"Mississauga",k:"Burgers",r:4.1},
    {n:"Foodie North",c:"Mississauga",k:"Asian",r:4.4},
    {n:"Noodle Wok",c:"Mississauga",k:"Asian",r:4.3},
    {n:"Masala Canteen",c:"Mississauga",k:"Asian",r:4.2},
    {n:"Al-Huda Restaurant",c:"Mississauga",k:"Pakistani",r:4.1},
    {n:"Shandra's Roti",c:"Mississauga",k:"Caribbean",r:4.5},
    {n:"Leela's Roti",c:"Mississauga",k:"Caribbean",r:4.4},
    {n:"Top Grill",c:"Mississauga",k:"Middle Eastern",r:4.6},
    {n:"Union Burger",c:"Mississauga",k:"Burgers",r:4.2},
    {n:"On The Bun",c:"Mississauga",k:"Burgers",r:4.5},
    {n:"Bao Sandwich Bar",c:"Mississauga",k:"Asian",r:4.6},
    {n:"Popeyes (Erin Mills)",c:"Mississauga",k:"Burgers",r:4.2},
    {n:"Popeyes (Hurontario)",c:"Mississauga",k:"Burgers",r:4.1},
    {n:"Mary Brown's (Dixie)",c:"Mississauga",k:"Burgers",r:4.4},
    {n:"Church's Chicken (Dundas)",c:"Mississauga",k:"Burgers",r:4.1},
    {n:"Pizza Pizza (Halal - Dixie)",c:"Mississauga",k:"Italian",r:3.8},
    {n:"Gino's Pizza (Halal)",c:"Mississauga",k:"Italian",r:4.1},
    {n:"Chili Chicken House",c:"Mississauga",k:"Asian",r:4.4},
    {n:"O'Frenchy",c:"Mississauga",k:"Burgers",r:4.1},
    {n:"Rollz Ice Cream",c:"Mississauga",k:"Dessert",r:4.5},
    {n:"Chocolato",c:"Mississauga",k:"Dessert",r:4.3},
    {n:"Beans & Grapes",c:"Mississauga",k:"Dessert",r:4.4},
    {n:"Coffee Time (Iraqi Style)",c:"Mississauga",k:"Dessert",r:4.1},
    {n:"Premium Sweets",c:"Mississauga",k:"Dessert",r:4.1},
    {n:"Shalimar",c:"Mississauga",k:"Dessert",r:4.2},

    // SCARBOROUGH / GOLDEN MILE
    {n:"Aleppo Kebab",c:"Scarborough",k:"Middle Eastern",r:4.6},
    {n:"Sumaq",c:"Scarborough",k:"Middle Eastern",r:4.7},
    {n:"Babu",c:"Scarborough",k:"Asian",r:4.5},
    {n:"Ghadir Meat",c:"Scarborough",k:"Middle Eastern",r:4.6},
    {n:"Nasib's",c:"Scarborough",k:"Middle Eastern",r:4.6},
    {n:"Shawarma Empire",c:"Scarborough",k:"Middle Eastern",r:4.5},
    {n:"Ibrahim BBQ",c:"Scarborough",k:"Middle Eastern",r:4.3},
    {n:"Al Ayoub",c:"Scarborough",k:"Egyptian",r:4.2},
    {n:"Sumilicious",c:"Scarborough",k:"Burgers",r:4.6},
    {n:"Northern Smokes",c:"Scarborough",k:"Burgers",r:4.7},
    {n:"Frederick",c:"Scarborough",k:"Asian",r:4.2},
    {n:"Charcoal Kebab",c:"Scarborough",k:"Asian",r:4.5},
    {n:"Fishman Lobster",c:"Scarborough",k:"Sushi",r:4.4},
    {n:"Diana's Seafood",c:"Scarborough",k:"Sushi",r:4.6},
    {n:"Mona's Roti",c:"Scarborough",k:"Caribbean",r:4.6},
    {n:"Chris Jerk",c:"Scarborough",k:"Caribbean",r:4.7},
    {n:"Sahan (Somali)",c:"Scarborough",k:"African",r:4.3},
    {n:"Ibiza Lounge",c:"Scarborough",k:"Masla7a",r:4.1},
    {n:"Fusion Lounge",c:"Scarborough",k:"Masla7a",r:4.2},
    {n:"Silver Spoon",c:"Scarborough",k:"Pakistani",r:4.1},
    {n:"Patna Kebab",c:"Scarborough",k:"Pakistani",r:4.3},
    {n:"Kebob City",c:"Scarborough",k:"Pakistani",r:4.2},
    {n:"Nihari Inn",c:"Scarborough",k:"Pakistani",r:4.2},
    {n:"Karachi Xpress",c:"Scarborough",k:"Pakistani",r:4.0},
    {n:"Kandahar Kabob",c:"Scarborough",k:"Middle Eastern",r:4.4},
    {n:"Naan & Kabob",c:"Scarborough",k:"Middle Eastern",r:4.2},
    {n:"Lin Garden",c:"Scarborough",k:"Asian",r:4.2},
    {n:"Kroran Uyghur",c:"Scarborough",k:"Asian",r:4.4},
    {n:"The Captain's Boil",c:"Scarborough",k:"Sushi",r:4.1},
    {n:"Sushi Legend",c:"Scarborough",k:"Sushi",r:4.2},
    {n:"Pizza Land",c:"Scarborough",k:"Italian",r:4.2},
    {n:"D Spot Dessert",c:"Scarborough",k:"Dessert",r:4.4},
    {n:"Kunafa's",c:"Scarborough",k:"Dessert",r:4.6},
    {n:"Twilight Cafe",c:"Scarborough",k:"Masla7a",r:4.3},
    {n:"Barans",c:"Scarborough",k:"Turkish",r:4.3},
    {n:"Bao Shin",c:"Scarborough",k:"Asian",r:4.3},
    {n:"Real McCoy",c:"Scarborough",k:"Burgers",r:4.5},
    {n:"Black Dutch",c:"Scarborough",k:"Burgers",r:4.3},
    {n:"Mama's Boys",c:"Scarborough",k:"Burgers",r:4.4},
    {n:"Taste of Uzbekistan",c:"Scarborough",k:"Asian",r:4.3},
    {n:"Karahi Boys",c:"Scarborough",k:"Pakistani",r:4.2},
    {n:"Tahini's",c:"Scarborough",k:"Middle Eastern",r:4.4},
    {n:"Sammy's",c:"Scarborough",k:"Burgers",r:4.2},
    {n:"Johnny's Hamburgers",c:"Scarborough",k:"Burgers",r:4.2},
    {n:"Hakka Garden",c:"Scarborough",k:"Asian",r:4.1},
    {n:"Federick Junction",c:"Scarborough",k:"Asian",r:4.2},
    {n:"Nile Lounge",c:"Scarborough",k:"Masla7a",r:4.0},
    {n:"Bismillah Brand",c:"Scarborough",k:"Pakistani",r:4.0},
    {n:"Iqbal Kebab",c:"Scarborough",k:"Pakistani",r:4.2},
    {n:"Lahore Premium Kebab",c:"Scarborough",k:"Pakistani",r:4.4},
    {n:"Pak Centre",c:"Scarborough",k:"Pakistani",r:4.1},
    {n:"Fahmee Bakery",c:"Scarborough",k:"Caribbean",r:4.5},
    {n:"Island Spice",c:"Scarborough",k:"Caribbean",r:4.3},
    {n:"Makkah Restaurant",c:"Scarborough",k:"Pakistani",r:4.2},
    {n:"Suya Spot",c:"Scarborough",k:"African",r:4.1},
    {n:"Popeyes (Lawrence E)",c:"Scarborough",k:"Burgers",r:4.0},
    {n:"Popeyes (Markham Rd)",c:"Scarborough",k:"Burgers",r:4.1},
    {n:"Mary Brown's (Morningside)",c:"Scarborough",k:"Burgers",r:4.5},
    {n:"KFC (Halal - Eglinton)",c:"Scarborough",k:"Burgers",r:3.9},
    {n:"Gingerman",c:"Scarborough",k:"Asian",r:4.2},
    {n:"Mainsha",c:"Scarborough",k:"Caribbean",r:4.1},
    {n:"Hogi Yogi",c:"Scarborough",k:"Burgers",r:4.3},
    {n:"Rollz Ice Cream",c:"Scarborough",k:"Dessert",r:4.5},
    {n:"Pizza Pizza (Halal - Markham)",c:"Scarborough",k:"Italian",r:3.8},
    {n:"Domino's (Halal - Lawrence)",c:"Scarborough",k:"Italian",r:4.0},
    {n:"Mamajoun",c:"Scarborough",k:"Italian",r:4.6},
    {n:"Furn-Saj",c:"Scarborough",k:"Middle Eastern",r:4.5},
    {n:"Chaiiwala of London",c:"Scarborough",k:"Dessert",r:4.2},
    {n:"Al-Kanaan",c:"Scarborough",k:"Middle Eastern",r:4.5},

    // TORONTO DOWNTOWN / CORE
    {n:"Ramen Isshin",c:"Toronto",k:"Asian",r:4.6},
    {n:"Illstyl3 Sammies",c:"Toronto",k:"Burgers",r:4.7},
    {n:"Chica's Chicken",c:"Toronto",k:"Burgers",r:4.7},
    {n:"Knockout Chicken",c:"Toronto",k:"Burgers",r:4.4},
    {n:"Tut's Egyptian",c:"Toronto",k:"Egyptian",r:4.5},
    {n:"Maha's Brunch",c:"Toronto",k:"Egyptian",r:4.7},
    {n:"Papyrus",c:"Toronto",k:"Egyptian",r:4.4},
    {n:"Eggstatic",c:"Toronto",k:"Egyptian",r:4.6},
    {n:"Salad King",c:"Toronto",k:"Asian",r:4.4},
    {n:"Sukhothai",c:"Toronto",k:"Asian",r:4.5},
    {n:"PAI",c:"Toronto",k:"Asian",r:4.7},
    {n:"Burgers Priest",c:"Toronto",k:"Burgers",r:4.3},
    {n:"Chen Chen's",c:"Toronto",k:"Burgers",r:4.6},
    {n:"Dave's Hot Chicken",c:"Toronto",k:"Burgers",r:4.5},
    {n:"PG Clucks",c:"Toronto",k:"Burgers",r:4.6},
    {n:"The Halal Guys",c:"Toronto",k:"Middle Eastern",r:4.1},
    {n:"Amal Toronto",c:"Toronto",k:"Middle Eastern",r:4.4},
    {n:"Kibo Sushi",c:"Toronto",k:"Sushi",r:4.3},
    {n:"Meat and Pie Co",c:"Toronto",k:"Steakhouse",r:4.5},
    {n:"6ix Pizzas",c:"Toronto",k:"Italian",r:4.4},
    {n:"Rasta Pasta",c:"Toronto",k:"Caribbean",r:4.5},
    {n:"Faryab Kabob",c:"Toronto",k:"Middle Eastern",r:4.6},
    {n:"Sheba Lounge",c:"Toronto",k:"Masla7a",r:4.3},
    {n:"Matt's Burger Lab",c:"Toronto",k:"Burgers",r:4.5},
    {n:"Lahore Tikka House",c:"Toronto",k:"Pakistani",r:4.0},
    {n:"Maker Pizza",c:"Toronto",k:"Italian",r:4.5},
    {n:"Blondies Pizza",c:"Toronto",k:"Italian",r:4.3},
    {n:"Chipotle",c:"Toronto",k:"Mexican",r:4.1},
    {n:"Evviva Breakfast",c:"Toronto",k:"Burgers",r:4.4},
    {n:"Fuwa Fuwa",c:"Toronto",k:"Dessert",r:4.3},
    {n:"Red Lobster",c:"Toronto",k:"Sushi",r:4.0},
    {n:"Barberian's (Req)",c:"Toronto",k:"Steakhouse",r:4.6},
    {n:"Jacob's Steakhouse (Req)",c:"Toronto",k:"Steakhouse",r:4.6},
    {n:"Sahara Cafe",c:"Toronto",k:"Masla7a",r:3.9},
    {n:"Pasha",c:"Toronto",k:"Turkish",r:4.2},
    {n:"Top Gun Burgers",c:"Toronto",k:"Burgers",r:4.3},
    {n:"Ozzy's Burgers",c:"Toronto",k:"Burgers",r:4.6},
    {n:"Holy Chuck",c:"Toronto",k:"Burgers",r:4.2},
    {n:"Storm Crow Manor",c:"Toronto",k:"Burgers",r:4.4},
    {n:"Scotty Bons",c:"Toronto",k:"Caribbean",r:4.3},
    {n:"Pizzaville",c:"Toronto",k:"Italian",r:4.2},
    {n:"Doner Kebab House",c:"Toronto",k:"Turkish",r:4.1},
    {n:"Istanbul Doner",c:"Toronto",k:"Turkish",r:4.2},
    {n:"Tabule",c:"Toronto",k:"Middle Eastern",r:4.5},
    {n:"Ali's Roti",c:"Toronto",k:"Caribbean",r:4.2},
    {n:"Island Foods",c:"Toronto",k:"Caribbean",r:4.5},
    {n:"Eat Banh Mi",c:"Toronto",k:"Asian",r:4.6},
    {n:"Gushi Japanese Chicken",c:"Toronto",k:"Asian",r:4.5},
    {n:"Samba Brazil",c:"Toronto",k:"Steakhouse",r:4.2},
    {n:"Le Burger",c:"Toronto",k:"Burgers",r:4.3},
    {n:"Naan & Chai",c:"Toronto",k:"Dessert",r:4.3},
    {n:"La Diperie",c:"Toronto",k:"Dessert",r:4.2},
    {n:"Butter Chicken Roti",c:"Toronto",k:"Pakistani",r:4.1},
    {n:"Roti King",c:"Toronto",k:"Asian",r:4.3},
    {n:"Makkah Restaurant",c:"Toronto",k:"Pakistani",r:4.3},
    {n:"Madina",c:"Toronto",k:"Pakistani",r:4.2},
    {n:"Yueh Tung",c:"Toronto",k:"Asian",r:4.5},
    {n:"Simons Wok",c:"Toronto",k:"Asian",r:4.2},
    {n:"Urban Maharajas",c:"Toronto",k:"Pakistani",r:4.3},
    {n:"Sizzling Wok",c:"Toronto",k:"Asian",r:4.1},
    {n:"The Poutine Supreme",c:"Toronto",k:"Burgers",r:4.4},

    // NORTH YORK / ETOBICOKE
    {n:"Meat Point",c:"North York",k:"Turkish",r:4.5},
    {n:"Mustafa",c:"North York",k:"Turkish",r:4.4},
    {n:"Burgers Park",c:"North York",k:"Burgers",r:4.5},
    {n:"Karahi Point",c:"North York",k:"Pakistani",r:4.1},
    {n:"Gyu-Kaku",c:"North York",k:"Asian",r:4.4},
    {n:"Omni Palace",c:"North York",k:"Asian",r:4.3},
    {n:"Magical Taste",c:"North York",k:"Asian",r:4.2},
    {n:"Nar Shisha",c:"North York",k:"Masla7a",r:4.6},
    {n:"70 Down",c:"North York",k:"Masla7a",r:4.1},
    {n:"Faley",c:"North York",k:"Asian",r:4.1},
    {n:"Jerusalem",c:"North York",k:"Middle Eastern",r:4.3},
    {n:"Paramount",c:"North York",k:"Middle Eastern",r:4.0},
    {n:"Pita Lite",c:"North York",k:"Middle Eastern",r:4.1},
    {n:"Sang-Ji Bao",c:"North York",k:"Asian",r:4.4},
    {n:"Konjiki Ramen",c:"North York",k:"Asian",r:4.5},
    {n:"Basil Box",c:"North York",k:"Asian",r:4.2},
    {n:"Pizzaiolo",c:"North York",k:"Italian",r:4.1},
    {n:"Osmow's",c:"North York",k:"Middle Eastern",r:3.9},
    {n:"Lazeez",c:"North York",k:"Middle Eastern",r:4.0},
    {n:"Union Social",c:"North York",k:"Burgers",r:4.2},
    {n:"Plan B",c:"Etobicoke",k:"Burgers",r:4.4},
    {n:"Momo's",c:"Etobicoke",k:"Asian",r:4.4},
    {n:"Hamdi",c:"Etobicoke",k:"African",r:4.2},
    {n:"Mushkaki",c:"Etobicoke",k:"African",r:4.3},
    {n:"Somali Restaurant",c:"Etobicoke",k:"African",r:4.1},
    {n:"Top Gun",c:"Etobicoke",k:"Burgers",r:4.3},
    {n:"Apache Burgers",c:"Etobicoke",k:"Burgers",r:4.4},
    {n:"Xawaash",c:"Etobicoke",k:"African",r:4.5},
    {n:"Istar Restaurant",c:"Etobicoke",k:"African",r:4.2},
    {n:"Mandimandi",c:"Etobicoke",k:"African",r:4.3},
    {n:"Church's Chicken (Steeles)",c:"North York",k:"Burgers",r:4.0},
    {n:"KFC (Halal - Keele)",c:"North York",k:"Burgers",r:3.8},
    {n:"Xawaash",c:"Etobicoke",k:"African",r:4.5},
    {n:"Istar Restaurant",c:"Etobicoke",k:"African",r:4.3},
    {n:"Mandimandi",c:"Etobicoke",k:"African",r:4.4},
    {n:"Salaama Hut",c:"Etobicoke",k:"African",r:4.4},
    {n:"Silk Road",c:"Etobicoke",k:"Asian",r:4.3},
    {n:"Al-Meezan",c:"Etobicoke",k:"Pakistani",r:4.1},
    {n:"Karahi Point",c:"Etobicoke",k:"Pakistani",r:4.2},
    {n:"Pizza Pizza (Albion Rd)",c:"Etobicoke",k:"Italian",r:3.9},
    {n:"Kandahar Kabob",c:"Etobicoke",k:"Middle Eastern",r:4.4},
    {n:"Bamiyan Kabob",c:"East York",k:"Middle Eastern",r:4.3},
    {n:"Island Foods",c:"North York",k:"Caribbean",r:4.5},

    // VAUGHAN / WOODBRIDGE
    {n:"Ozzy's Burgers",c:"Vaughan",k:"Burgers",r:4.7},
    {n:"Ricci's Pizzeria",c:"Vaughan",k:"Italian",r:4.3},
    {n:"Memon Fire",c:"Vaughan",k:"Pakistani",r:4.2},
    {n:"Top Gun Burgers",c:"Vaughan",k:"Burgers",r:4.4},
    {n:"Bergham",c:"Vaughan",k:"Burgers",r:4.1},
    {n:"Bamiyan Kabob",c:"Vaughan",k:"Middle Eastern",r:4.3},
    {n:"Champion Doner",c:"Vaughan",k:"Turkish",r:4.5},
    {n:"Karahi Boys",c:"Vaughan",k:"Pakistani",r:4.2},
    {n:"Memphis BBQ",c:"Vaughan",k:"Steakhouse",r:4.4},
    {n:"Scaddabush",c:"Vaughan",k:"Italian",r:4.3},
    {n:"Pi Co.",c:"Vaughan",k:"Italian",r:4.6},
    {n:"Holy Shakes",c:"Vaughan",k:"Dessert",r:4.5},
    {n:"Haze Lounge",c:"Vaughan",k:"Masla7a",r:4.2},
    {n:"Classic Cafe",c:"Vaughan",k:"Masla7a",r:4.7},
    {n:"OMNIA Lounge",c:"Vaughan",k:"Masla7a",r:4.4},
    {n:"Ay Caramba",c:"Vaughan",k:"Mexican",r:4.7},
    {n:"Gladiator Burger",c:"Vaughan",k:"Burgers",r:4.5},
    {n:"Burgers Priest",c:"Vaughan",k:"Burgers",r:4.2},
    {n:"Pita Land",c:"Vaughan",k:"Middle Eastern",r:4.1},
    {n:"Chi",c:"Vaughan",k:"Asian",r:4.3},
    {n:"The Captain's Boil",c:"Vaughan",k:"Sushi",r:4.2},
    {n:"Red Lobster",c:"Vaughan",k:"Sushi",r:4.0},
    {n:"Blackstone Steakhouse",c:"Vaughan",k:"Steakhouse",r:4.2},
    {n:"Pizza Nova",c:"Vaughan",k:"Italian",r:4.1},
    {n:"Habaneros",c:"Vaughan",k:"Mexican",r:4.2},
    {n:"Super Chicken",c:"Vaughan",k:"Burgers",r:4.3},
    {n:"Dessert Trends",c:"Vaughan",k:"Dessert",r:4.4},
    {n:"La Palma",c:"Vaughan",k:"Italian",r:4.2},
    {n:"South St. Burger",c:"Vaughan",k:"Burgers",r:4.2},
    {n:"Crepe Star",c:"Vaughan",k:"Dessert",r:4.3},
    {n:"Berlin Doner",c:"Vaughan",k:"Turkish",r:4.1},
    {n:"German Doner Kebab",c:"Vaughan",k:"Turkish",r:4.3},
    {n:"Burger Bros",c:"Vaughan",k:"Burgers",r:4.6},
    {n:"Holy Chuck (Hwy 7)",c:"Vaughan",k:"Burgers",r:4.4},
    {n:"South St. Burger (Rutherford)",c:"Vaughan",k:"Burgers",r:4.2},
    {n:"Odd Burger (Vegan/Halal)",c:"Vaughan",k:"Burgers",r:4.7},
    {n:"Hero Certified Burgers (Weston)",c:"Vaughan",k:"Burgers",r:4.1},
    {n:"Hero Certified Burgers (Major Mack)",c:"Vaughan",k:"Burgers",r:4.0},
    {n:"Chicken Plus",c:"Vaughan",k:"Burgers",r:4.5},
    {n:"St. Louis Bar & Grill (Halal Wings)",c:"Vaughan",k:"Burgers",r:4.1},
    {n:"Wild Wing (Rutherford)",c:"Vaughan",k:"Burgers",r:4.0},
    {n:"Wingstop (Jane St)",c:"Vaughan",k:"Burgers",r:4.2},
    {n:"Church's Chicken (Hwy 27)",c:"Vaughan",k:"Burgers",r:4.0},
    {n:"Mary Brown's (Major Mack)",c:"Vaughan",k:"Burgers",r:4.3},
    {n:"Pita Golden Pocket (Vaughan loc)",c:"Vaughan",k:"Middle Eastern",r:4.7},
    {n:"Osmow's (Weston Rd)",c:"Vaughan",k:"Middle Eastern",r:3.9},
    {n:"Osmow's (Major Mack)",c:"Vaughan",k:"Middle Eastern",r:3.8},
    {n:"Lazeez (Rutherford)",c:"Vaughan",k:"Middle Eastern",r:4.0},
    {n:"Lazeez (Jane St)",c:"Vaughan",k:"Middle Eastern",r:3.9},
    {n:"Shawarma Royale",c:"Vaughan",k:"Middle Eastern",r:4.3},
    {n:"Pita & Grill (Vaughan)",c:"Vaughan",k:"Middle Eastern",r:4.2},
    {n:"Tahini's (Vaughan Mills)",c:"Vaughan",k:"Middle Eastern",r:4.4},
    {n:"Me Va Me (Halal Options)",c:"Vaughan",k:"Middle Eastern",r:4.3},
    {n:"Meron To Go",c:"Vaughan",k:"Middle Eastern",r:4.5},
    {n:"Jerusalem Restaurant",c:"Vaughan",k:"Middle Eastern",r:4.3},
    {n:"Pizzaiolo (Rutherford)",c:"Vaughan",k:"Italian",r:4.2},
    {n:"Pizzaiolo (Major Mack)",c:"Vaughan",k:"Italian",r:4.1},
    {n:"Pizza Pizza (Halal - Weston)",c:"Vaughan",k:"Italian",r:3.8},
    {n:"Pizza Nova (Halal - Hwy 27)",c:"Vaughan",k:"Italian",r:4.2},
    {n:"Gino's Pizza (Vaughan)",c:"Vaughan",k:"Italian",r:4.0},
    {n:"Abruzzo Pizza",c:"Vaughan",k:"Italian",r:4.4},
    {n:"Motorino Enoteca",c:"Vaughan",k:"Italian",r:4.3},
    {n:"Thai Express (Vaughan Mills)",c:"Vaughan",k:"Asian",r:3.9},
    {n:"Szechuan Szechuan",c:"Vaughan",k:"Asian",r:4.2},
    {n:"Teriyaki Experience",c:"Vaughan",k:"Asian",r:3.8},
    {n:"Manchu Wok (Halal Opt)",c:"Vaughan",k:"Asian",r:3.7},
    {n:"Pho Metro (Halal Opt)",c:"Vaughan",k:"Asian",r:4.4},
    {n:"King Tandoori (Hwy 27)",c:"Vaughan",k:"Pakistani",r:4.1},
    {n:"Avani Asian Indian",c:"Vaughan",k:"Pakistani",r:4.3},
    {n:"Bombay Touch",c:"Vaughan",k:"Pakistani",r:4.2},
    {n:"My Roti Place (Vaughan)",c:"Vaughan",k:"Pakistani",r:4.1},
    {n:"Sugar Marmalade",c:"Vaughan",k:"Dessert",r:4.2},
    {n:"Heaven's Gelato",c:"Vaughan",k:"Dessert",r:4.6},
    {n:"Love Gelato",c:"Vaughan",k:"Dessert",r:4.5},
    {n:"Caffe Demetre",c:"Vaughan",k:"Dessert",r:4.3},
    {n:"Chocolats Favoris",c:"Vaughan",k:"Dessert",r:4.6},
    {n:"Aroma Espresso Bar",c:"Vaughan",k:"Dessert",r:4.2},
    {n:"Cafe De Paix",c:"Vaughan",k:"Masla7a",r:4.3},
    {n:"Vibe Lounge",c:"Vaughan",k:"Masla7a",r:4.1},
    {n:"Sensation Lounge",c:"Vaughan",k:"Masla7a",r:4.0},
    {n:"Popeyes (Rutherford)",c:"Vaughan",k:"Burgers",r:4.1},
    {n:"Mary Brown's (Dufferin)",c:"Vaughan",k:"Burgers",r:4.3},
    {n:"La Diperie",c:"Vaughan",k:"Dessert",r:4.2},

    // AURORA
    {n:"Pita Golden Pocket",c:"Aurora",k:"Middle Eastern",r:4.8},
    {n:"Gladiator Burger",c:"Aurora",k:"Burgers",r:4.5},
    {n:"Bamiyan Kabob",c:"Aurora",k:"Middle Eastern",r:4.3},
    {n:"Mary Brown's",c:"Aurora",k:"Burgers",r:4.4},
    {n:"Minami Sushi",c:"Aurora",k:"Sushi",r:4.4},
    {n:"Fishbone Kitchen",c:"Aurora",k:"Sushi",r:4.5},
    {n:"Shawarma Land",c:"Aurora",k:"Middle Eastern",r:4.2},
    {n:"Bombay's Chutney",c:"Aurora",k:"Pakistani",r:4.1},
    {n:"Kibo Sushi",c:"Aurora",k:"Sushi",r:4.3},
    {n:"Hero Certified",c:"Aurora",k:"Burgers",r:4.1},
    {n:"Wimpy's Diner",c:"Aurora",k:"Burgers",r:4.0},
    {n:"Swiss Chalet",c:"Aurora",k:"Burgers",r:4.0},
    {n:"Locale",c:"Aurora",k:"Italian",r:4.3},
    {n:"Symposium Cafe",c:"Aurora",k:"Dessert",r:4.2},

    // RICHMOND HILL
    {n:"Chef Reza",c:"Richmond Hill",k:"Middle Eastern",r:4.4},
    {n:"Tahini's",c:"Richmond Hill",k:"Middle Eastern",r:4.5},
    {n:"Pizza Shab",c:"Richmond Hill",k:"Italian",r:4.3},
    {n:"Joe's Hamburgers",c:"Richmond Hill",k:"Burgers",r:4.5},
    {n:"Roses Kebab",c:"Richmond Hill",k:"Middle Eastern",r:4.2},
    {n:"Shinta Japanese",c:"Richmond Hill",k:"Asian",r:4.4},
    {n:"QJD Peking Duck",c:"Richmond Hill",k:"Asian",r:4.3},
    {n:"Mandala Cafe",c:"Richmond Hill",k:"Masla7a",r:4.5},
    {n:"Cyan Cafe",c:"Richmond Hill",k:"Masla7a",r:4.2},
    {n:"Mado",c:"Richmond Hill",k:"Turkish",r:4.2},
    {n:"Mi-Ne Sushi",c:"Richmond Hill",k:"Sushi",r:4.3},
    {n:"Bar Burrito",c:"Richmond Hill",k:"Mexican",r:4.0},
    {n:"Chreston",c:"Richmond Hill",k:"Italian",r:4.2},
    {n:"Aneal's",c:"Richmond Hill",k:"Caribbean",r:4.4},
    {n:"Restoran Malaysia",c:"Richmond Hill",k:"Asian",r:4.3},
    {n:"Toppings",c:"Richmond Hill",k:"Burgers",r:4.2},
    {n:"Bamiyan Kabob",c:"Richmond Hill",k:"Middle Eastern",r:4.2},
    {n:"Big Trio Wonton",c:"Richmond Hill",k:"Asian",r:4.3},
    {n:"Chillax Coffee",c:"Richmond Hill",k:"Dessert",r:4.4},
    {n:"Tirbeh",c:"Richmond Hill",k:"Middle Eastern",r:4.3},
    {n:"Popeyes (Major Mack)",c:"Richmond Hill",k:"Burgers",r:4.0},

    // MARKHAM / AJAX / MILTON / BURLINGTON / WHITBY
    {n:"D Spot Dessert",c:"Markham",k:"Dessert",r:4.4},
    {n:"Bamiyan Kabob",c:"Markham",k:"Middle Eastern",r:4.3},
    {n:"Potbelly's",c:"Markham",k:"Egyptian",r:4.3},
    {n:"Malt N Salt",c:"Milton",k:"Burgers",r:4.6},
    {n:"Marquee Steak",c:"Milton",k:"Steakhouse",r:4.4},
    {n:"Adonis",c:"Oakville",k:"Middle Eastern",r:4.3},
    {n:"Chef's Door",c:"Oakville",k:"Middle Eastern",r:4.2},
    {n:"Monaghan's",c:"Oakville",k:"Burgers",r:4.1},
    {n:"Sultan's",c:"Oakville",k:"Turkish",r:4.4},
    {n:"D Spot Dessert",c:"Ajax",k:"Dessert",r:4.3},
    {n:"Karachi Xpress",c:"Ajax",k:"Pakistani",r:4.0},
    {n:"Affy's Premium",c:"Ajax",k:"Steakhouse",r:4.2},
    {n:"Shamrock",c:"Ajax",k:"Burgers",r:4.3},
    {n:"Pitalicious",c:"Markham",k:"Middle Eastern",r:4.4},
    {n:"Barakas",c:"Markham",k:"Middle Eastern",r:4.3},
    {n:"Hakka Wok",c:"Milton",k:"Asian",r:4.2},
    {n:"Pizzaville",c:"Ajax",k:"Italian",r:4.1},
    {n:"Pizza Pizza",c:"Ajax",k:"Italian",r:3.8},
    {n:"Kelsey's",c:"Ajax",k:"Burgers",r:4.0},
    {n:"Chuck's Roadhouse",c:"Ajax",k:"Steakhouse",r:3.9},
    {n:"Mount Zion",c:"Pickering",k:"Caribbean",r:4.4},
    {n:"Big M Burgers",c:"Pickering",k:"Burgers",r:4.3},
    {n:"Yardies",c:"Pickering",k:"Caribbean",r:4.2},
    {n:"Gladiator Burger",c:"Oakville",k:"Burgers",r:4.5},
    {n:"Kibo Sushi",c:"Oakville",k:"Sushi",r:4.3},
    {n:"50 Pesh",c:"Burlington",k:"Burgers",r:4.6},
    {n:"Gladiator Burger",c:"Burlington",k:"Burgers",r:4.5},
    {n:"D Spot Dessert",c:"Burlington",k:"Dessert",r:4.4},
    {n:"Burger Priest",c:"Oakville",k:"Burgers",r:4.2},
    {n:"D Spot Dessert",c:"Whitby",k:"Dessert",r:4.3},
    {n:"Bang Bang Burrito",c:"Oshawa",k:"Mexican",r:4.5},
    {n:"Osmow's",c:"Whitby",k:"Middle Eastern",r:3.9},
    {n:"Mary Brown's",c:"Whitby",k:"Burgers",r:4.2},
    {n:"Popeyes",c:"Ajax",k:"Burgers",r:4.0},
    {n:"Doner & Gyros",c:"Ajax",k:"Turkish",r:4.2},
    {n:"Federick (Markham)",c:"Markham",k:"Asian",r:4.2},
    {n:"Tangerine Asian",c:"Markham",k:"Asian",r:4.3}
];