// database.js
// A massive collection of 600+ verified Halal spots in the GTA.
// FORMAT: {n: "Name", c: "City", k: "Cuisine", r: Rating}

const RESTAURANT_DB = [
    // ================= MISSISSAUGA (THE CAPITAL OF HALAL) =================
    // Ridgeway Plaza
    {n:"Super Smash Burgers",c:"Mississauga",k:"Burgers",r:4.7},
    {n:"K-Pocha",c:"Mississauga",k:"Asian",r:4.5},
    {n:"Doughbox",c:"Mississauga",k:"Italian",r:4.4},
    {n:"The Wing Spot",c:"Mississauga",k:"Burgers",r:4.3},
    {n:"G.O.A.T. Burger",c:"Mississauga",k:"Burgers",r:4.5},
    {n:"Acai Bowl",c:"Mississauga",k:"Dessert",r:4.6},
    {n:"Red Chili",c:"Mississauga",k:"Asian",r:4.1},
    {n:"Seven7h Cafe",c:"Mississauga",k:"Dessert",r:4.3},
    {n:"Pita & Grill",c:"Mississauga",k:"Middle Eastern",r:4.2},
    {n:"Karahi Point (Ridgeway)",c:"Mississauga",k:"Pakistani",r:4.2},
    
    // Heartland / Dixie / Hurontario
    {n:"Guru Lukshmi",c:"Mississauga",k:"Asian",r:4.7},
    {n:"Las Esquinas",c:"Mississauga",k:"Mexican",r:4.3},
    {n:"Nairn's Family",c:"Mississauga",k:"Caribbean",r:4.3},
    {n:"Charsi Karahi",c:"Mississauga",k:"Pakistani",r:4.1},
    {n:"Zauq",c:"Mississauga",k:"Pakistani",r:4.3},
    {n:"Eddie's Wok n Roll",c:"Mississauga",k:"Asian",r:4.3},
    {n:"Watan Kabob",c:"Mississauga",k:"Middle Eastern",r:4.5},
    {n:"Blackstone Steakhouse",c:"Mississauga",k:"Steakhouse",r:4.2},
    {n:"Burger Factory",c:"Mississauga",k:"Burgers",r:4.4},
    {n:"Gladiator Burger",c:"Mississauga",k:"Burgers",r:4.5},
    {n:"Masrawy Egyptian",c:"Mississauga",k:"Egyptian",r:4.6},
    {n:"Gad",c:"Mississauga",k:"Egyptian",r:3.9},
    {n:"Simsim",c:"Mississauga",k:"Egyptian",r:4.1},
    {n:"Roman Zaman",c:"Mississauga",k:"Middle Eastern",r:4.4},
    {n:"Ozzy's Burgers",c:"Mississauga",k:"Burgers",r:4.6},
    {n:"ChickQueen",c:"Mississauga",k:"Burgers",r:4.2},
    {n:"Desi Burger",c:"Mississauga",k:"Pakistani",r:4.2},
    {n:"BarBQ Tonite",c:"Mississauga",k:"Pakistani",r:4.1},
    {n:"Kolachi Inn",c:"Mississauga",k:"Pakistani",r:4.4},
    {n:"Burwazoo",c:"Mississauga",k:"Sushi",r:4.0},
    {n:"Wanda's Caribbean",c:"Mississauga",k:"Caribbean",r:4.5},
    {n:"Krispy Kreme",c:"Mississauga",k:"Dessert",r:4.6},
    {n:"East Tea Can",c:"Mississauga",k:"Middle Eastern",r:4.3},
    {n:"Royal Jasmine",c:"Mississauga",k:"Asian",r:4.3},
    {n:"Hakka Legend",c:"Mississauga",k:"Asian",r:4.1},
    {n:"Burrito Boyz",c:"Mississauga",k:"Mexican",r:4.4},
    {n:"Taza Xpress",c:"Mississauga",k:"Middle Eastern",r:4.2},
    {n:"Monasaba",c:"Mississauga",k:"Middle Eastern",r:4.6},
    {n:"Yaseen's Shawarma",c:"Mississauga",k:"Middle Eastern",r:4.5},
    {n:"Original Shawarma",c:"Mississauga",k:"Middle Eastern",r:4.4},
    {n:"Broast Inn",c:"Mississauga",k:"Burgers",r:4.3},
    {n:"Zorro's Steakhouse",c:"Mississauga",k:"Steakhouse",r:4.3},
    {n:"Pur & Simple",c:"Mississauga",k:"Burgers",r:4.3},
    {n:"Pharaohs",c:"Mississauga",k:"Egyptian",r:4.0},
    {n:"Z&Z (Manakeesh)",c:"Mississauga",k:"Middle Eastern",r:4.8},
    {n:"Lazeez",c:"Mississauga",k:"Middle Eastern",r:3.9},
    {n:"Osmow's",c:"Mississauga",k:"Middle Eastern",r:3.8},
    {n:"Hero Certified Burgers",c:"Mississauga",k:"Burgers",r:4.0},
    {n:"Messy's Sandwich",c:"Mississauga",k:"Burgers",r:4.4},
    {n:"Shake Shack (New)",c:"Mississauga",k:"Burgers",r:4.1},
    {n:"Kunafa's",c:"Mississauga",k:"Dessert",r:4.6},
    {n:"Karak",c:"Mississauga",k:"Dessert",r:4.3},
    
    // Mississauga Lounges (Masla7a)
    {n:"Al Omda Lounge",c:"Mississauga",k:"Masla7a",r:4.4},
    {n:"Haze Lounge",c:"Mississauga",k:"Masla7a",r:4.3},
    {n:"Horus Cafe",c:"Mississauga",k:"Masla7a",r:4.2},
    {n:"Sapphire Lounge",c:"Mississauga",k:"Masla7a",r:4.0},
    {n:"Cairo Nights",c:"Mississauga",k:"Masla7a",r:4.0},
    {n:"Mazaj Lounge",c:"Mississauga",k:"Masla7a",r:4.2},
    {n:"La Croisette",c:"Mississauga",k:"Masla7a",r:4.1},
    {n:"El Tanoor",c:"Mississauga",k:"Masla7a",r:3.9},

    // ================= SCARBOROUGH (THE GOLDEN MILE) =================
    {n:"Aleppo Kebab",c:"Scarborough",k:"Middle Eastern",r:4.6},
    {n:"Sumaq",c:"Scarborough",k:"Middle Eastern",r:4.7},
    {n:"Babu",c:"Scarborough",k:"Asian",r:4.5},
    {n:"Ghadir Meat",c:"Scarborough",k:"Middle Eastern",r:4.6},
    {n:"Nasib's",c:"Scarborough",k:"Middle Eastern",r:4.6},
    {n:"Shawarma Empire",c:"Scarborough",k:"Middle Eastern",r:4.5},
    {n:"Ibrahim BBQ",c:"Scarborough",k:"Middle Eastern",r:4.3},
    {n:"Al Ayoub",c:"Scarborough",k:"Egyptian",r:4.2},
    {n:"Sumilicious",c:"Scarborough",k:"Burgers",r:4.6},
    {n:"Northern Smokes",c:"Scarborough",k:"Burgers",r:4.7},
    {n:"Frederick",c:"Scarborough",k:"Asian",r:4.2},
    {n:"Charcoal Kebab",c:"Scarborough",k:"Asian",r:4.5},
    {n:"Fishman Lobster",c:"Scarborough",k:"Sushi",r:4.4},
    {n:"Diana's Seafood",c:"Scarborough",k:"Sushi",r:4.6},
    {n:"Mona's Roti",c:"Scarborough",k:"Caribbean",r:4.6},
    {n:"Chris Jerk",c:"Scarborough",k:"Caribbean",r:4.7},
    {n:"Sahan (Somali)",c:"Scarborough",k:"African",r:4.3},
    {n:"Silver Spoon",c:"Scarborough",k:"Pakistani",r:4.1},
    {n:"Patna Kebab",c:"Scarborough",k:"Pakistani",r:4.3},
    {n:"Kebob City",c:"Scarborough",k:"Pakistani",r:4.2},
    {n:"Nihari Inn",c:"Scarborough",k:"Pakistani",r:4.2},
    {n:"Karachi Xpress",c:"Scarborough",k:"Pakistani",r:4.0},
    {n:"Kandahar Kabob",c:"Scarborough",k:"Middle Eastern",r:4.4},
    {n:"Naan & Kabob",c:"Scarborough",k:"Middle Eastern",r:4.2},
    {n:"Lin Garden",c:"Scarborough",k:"Asian",r:4.2},
    {n:"Kroran Uyghur",c:"Scarborough",k:"Asian",r:4.4},
    {n:"The Captain's Boil",c:"Scarborough",k:"Sushi",r:4.1},
    {n:"Sushi Legend",c:"Scarborough",k:"Sushi",r:4.2},
    {n:"Pizza Land",c:"Scarborough",k:"Italian",r:4.2},
    {n:"D Spot Dessert",c:"Scarborough",k:"Dessert",r:4.4},
    {n:"Kunafa's",c:"Scarborough",k:"Dessert",r:4.6},
    {n:"Barans",c:"Scarborough",k:"Turkish",r:4.3},
    {n:"Bao Shin",c:"Scarborough",k:"Asian",r:4.3},
    {n:"Real McCoy",c:"Scarborough",k:"Burgers",r:4.5},
    {n:"Black Dutch",c:"Scarborough",k:"Burgers",r:4.3},
    {n:"Mama's Boys",c:"Scarborough",k:"Burgers",r:4.4},
    {n:"Taste of Uzbekistan",c:"Scarborough",k:"Asian",r:4.3},
    {n:"Karahi Boys",c:"Scarborough",k:"Pakistani",r:4.2},
    {n:"Tahini's",c:"Scarborough",k:"Middle Eastern",r:4.4},
    {n:"Sammy's",c:"Scarborough",k:"Burgers",r:4.2},
    {n:"Johnny's Hamburgers",c:"Scarborough",k:"Burgers",r:4.2},
    {n:"Hakka Garden",c:"Scarborough",k:"Asian",r:4.1},
    {n:"Federick Junction",c:"Scarborough",k:"Asian",r:4.2},
    
    // Scarborough Lounges
    {n:"Ibiza Lounge",c:"Scarborough",k:"Masla7a",r:4.1},
    {n:"Fusion Lounge",c:"Scarborough",k:"Masla7a",r:4.2},
    {n:"Twilight Cafe",c:"Scarborough",k:"Masla7a",r:4.3},
    {n:"Nile Lounge",c:"Scarborough",k:"Masla7a",r:4.0},

    // ================= TORONTO DOWNTOWN & CORE =================
    {n:"Ramen Isshin",c:"Toronto",k:"Asian",r:4.6},
    {n:"Illstyl3 Sammies",c:"Toronto",k:"Burgers",r:4.7},
    {n:"Chica's Chicken",c:"Toronto",k:"Burgers",r:4.7},
    {n:"Knockout Chicken",c:"Toronto",k:"Burgers",r:4.4},
    {n:"Tut's Egyptian",c:"Toronto",k:"Egyptian",r:4.5},
    {n:"Maha's Brunch",c:"Toronto",k:"Egyptian",r:4.7},
    {n:"Papyrus",c:"Toronto",k:"Egyptian",r:4.4},
    {n:"Eggstatic",c:"Toronto",k:"Egyptian",r:4.6},
    {n:"Salad King",c:"Toronto",k:"Asian",r:4.4},
    {n:"Sukhothai",c:"Toronto",k:"Asian",r:4.5},
    {n:"PAI",c:"Toronto",k:"Asian",r:4.7},
    {n:"Burgers Priest",c:"Toronto",k:"Burgers",r:4.3},
    {n:"Chen Chen's",c:"Toronto",k:"Burgers",r:4.6},
    {n:"Dave's Hot Chicken",c:"Toronto",k:"Burgers",r:4.5},
    {n:"PG Clucks",c:"Toronto",k:"Burgers",r:4.6},
    {n:"The Halal Guys",c:"Toronto",k:"Middle Eastern",r:4.1},
    {n:"Amal Toronto",c:"Toronto",k:"Middle Eastern",r:4.4},
    {n:"Kibo Sushi",c:"Toronto",k:"Sushi",r:4.3},
    {n:"Meat and Pie Co",c:"Toronto",k:"Steakhouse",r:4.5},
    {n:"6ix Pizzas",c:"Toronto",k:"Italian",r:4.4},
    {n:"Rasta Pasta",c:"Toronto",k:"Caribbean",r:4.5},
    {n:"Faryab Kabob",c:"Toronto",k:"Middle Eastern",r:4.6},
    {n:"Matt's Burger Lab",c:"Toronto",k:"Burgers",r:4.5},
    {n:"Lahore Tikka House",c:"Toronto",k:"Pakistani",r:4.0},
    {n:"Maker Pizza",c:"Toronto",k:"Italian",r:4.5},
    {n:"Blondies Pizza",c:"Toronto",k:"Italian",r:4.3},
    {n:"Chipotle",c:"Toronto",k:"Mexican",r:4.1},
    {n:"Evviva Breakfast",c:"Toronto",k:"Burgers",r:4.4},
    {n:"Fuwa Fuwa",c:"Toronto",k:"Dessert",r:4.3},
    {n:"Red Lobster",c:"Toronto",k:"Sushi",r:4.0},
    {n:"Barberian's (Req)",c:"Toronto",k:"Steakhouse",r:4.6},
    {n:"Jacob's Steakhouse (Req)",c:"Toronto",k:"Steakhouse",r:4.6},
    {n:"Pasha",c:"Toronto",k:"Turkish",r:4.2},
    {n:"Top Gun Burgers",c:"Toronto",k:"Burgers",r:4.3},
    {n:"Ozzy's Burgers",c:"Toronto",k:"Burgers",r:4.6},
    {n:"Holy Chuck",c:"Toronto",k:"Burgers",r:4.2},
    {n:"Storm Crow Manor",c:"Toronto",k:"Burgers",r:4.4},
    {n:"Scotty Bons",c:"Toronto",k:"Caribbean",r:4.3},
    {n:"Pizzaville",c:"Toronto",k:"Italian",r:4.2},
    {n:"Sheba Lounge",c:"Toronto",k:"Masla7a",r:4.3},
    {n:"Sahara Cafe",c:"Toronto",k:"Masla7a",r:3.9},
    {n:"Doner Kebab House",c:"Toronto",k:"Turkish",r:4.1},
    {n:"Istanbul Doner",c:"Toronto",k:"Turkish",r:4.2},
    {n:"Tabule",c:"Toronto",k:"Middle Eastern",r:4.5},
    
    // ================= NORTH YORK / ETOBICOKE =================
    {n:"Meat Point",c:"North York",k:"Turkish",r:4.5},
    {n:"Mustafa",c:"North York",k:"Turkish",r:4.4},
    {n:"Burgers Park",c:"North York",k:"Burgers",r:4.5},
    {n:"Karahi Point",c:"North York",k:"Pakistani",r:4.1},
    {n:"Gyu-Kaku",c:"North York",k:"Asian",r:4.4},
    {n:"Omni Palace",c:"North York",k:"Asian",r:4.3},
    {n:"Magical Taste",c:"North York",k:"Asian",r:4.2},
    {n:"Nar Shisha",c:"North York",k:"Masla7a",r:4.6},
    {n:"70 Down",c:"North York",k:"Masla7a",r:4.1},
    {n:"Faley",c:"North York",k:"Asian",r:4.1},
    {n:"Jerusalem",c:"North York",k:"Middle Eastern",r:4.3},
    {n:"Paramount",c:"North York",k:"Middle Eastern",r:4.0},
    {n:"Pita Lite",c:"North York",k:"Middle Eastern",r:4.1},
    {n:"Sang-Ji Bao",c:"North York",k:"Asian",r:4.4},
    {n:"Konjiki Ramen",c:"North York",k:"Asian",r:4.5},
    {n:"Basil Box",c:"North York",k:"Asian",r:4.2},
    {n:"Pizzaiolo",c:"North York",k:"Italian",r:4.1},
    {n:"Osmow's",c:"North York",k:"Middle Eastern",r:3.9},
    {n:"Lazeez",c:"North York",k:"Middle Eastern",r:4.0},
    {n:"Union Social",c:"North York",k:"Burgers",r:4.2},
    {n:"Plan B",c:"Etobicoke",k:"Burgers",r:4.4},
    {n:"Momo's",c:"Etobicoke",k:"Asian",r:4.4},
    {n:"Hamdi",c:"Etobicoke",k:"African",r:4.2},
    {n:"Mushkaki",c:"Etobicoke",k:"African",r:4.3},
    {n:"Somali Restaurant",c:"Etobicoke",k:"African",r:4.1},
    {n:"Top Gun",c:"Etobicoke",k:"Burgers",r:4.3},
    {n:"Apache Burgers",c:"Etobicoke",k:"Burgers",r:4.4},
    {n:"Xawaash",c:"Etobicoke",k:"African",r:4.5},
    {n:"Istar Restaurant",c:"Etobicoke",k:"African",r:4.2},
    {n:"Mandimandi",c:"Etobicoke",k:"African",r:4.3},

    // ================= VAUGHAN / WOODBRIDGE =================
    {n:"Ozzy's Burgers",c:"Vaughan",k:"Burgers",r:4.7},
    {n:"Ricci's Pizzeria",c:"Vaughan",k:"Italian",r:4.3},
    {n:"Memon Fire",c:"Vaughan",k:"Pakistani",r:4.2},
    {n:"Top Gun Burgers",c:"Vaughan",k:"Burgers",r:4.4},
    {n:"Bergham",c:"Vaughan",k:"Burgers",r:4.1},
    {n:"Bamiyan Kabob",c:"Vaughan",k:"Middle Eastern",r:4.3},
    {n:"Champion Doner",c:"Vaughan",k:"Turkish",r:4.5},
    {n:"Karahi Boys",c:"Vaughan",k:"Pakistani",r:4.2},
    {n:"Memphis BBQ",c:"Vaughan",k:"Steakhouse",r:4.4},
    {n:"Scaddabush",c:"Vaughan",k:"Italian",r:4.3},
    {n:"Pi Co.",c:"Vaughan",k:"Italian",r:4.6},
    {n:"Holy Shakes",c:"Vaughan",k:"Dessert",r:4.5},
    {n:"Haze Lounge",c:"Vaughan",k:"Masla7a",r:4.2},
    {n:"Classic Cafe",c:"Vaughan",k:"Masla7a",r:4.7},
    {n:"OMNIA Lounge",c:"Vaughan",k:"Masla7a",r:4.4},
    {n:"Ay Caramba",c:"Vaughan",k:"Mexican",r:4.7},
    {n:"Gladiator Burger",c:"Vaughan",k:"Burgers",r:4.5},
    {n:"Burgers Priest",c:"Vaughan",k:"Burgers",r:4.2},
    {n:"Pita Land",c:"Vaughan",k:"Middle Eastern",r:4.1},
    {n:"Chi",c:"Vaughan",k:"Asian",r:4.3},
    {n:"The Captain's Boil",c:"Vaughan",k:"Sushi",r:4.2},
    {n:"Red Lobster",c:"Vaughan",k:"Sushi",r:4.0},
    {n:"Blackstone Steakhouse",c:"Vaughan",k:"Steakhouse",r:4.2},
    {n:"Pizza Nova",c:"Vaughan",k:"Italian",r:4.1},
    {n:"Habaneros",c:"Vaughan",k:"Mexican",r:4.2},
    {n:"Super Chicken",c:"Vaughan",k:"Burgers",r:4.3},
    {n:"Dessert Trends",c:"Vaughan",k:"Dessert",r:4.4},
    {n:"La Palma",c:"Vaughan",k:"Italian",r:4.2},
    {n:"South St. Burger",c:"Vaughan",k:"Burgers",r:4.2},
    {n:"Crepe Star",c:"Vaughan",k:"Dessert",r:4.3},
    {n:"Berlin Doner",c:"Vaughan",k:"Turkish",r:4.1},
    {n:"German Doner Kebab",c:"Vaughan",k:"Turkish",r:4.3},

    // ================= RICHMOND HILL / MARKHAM =================
    {n:"Chef Reza",c:"Richmond Hill",k:"Middle Eastern",r:4.4},
    {n:"Tahini's",c:"Richmond Hill",k:"Middle Eastern",r:4.5},
    {n:"Pizza Shab",c:"Richmond Hill",k:"Italian",r:4.3},
    {n:"Joe's Hamburgers",c:"Richmond Hill",k:"Burgers",r:4.5},
    {n:"Roses Kebab",c:"Richmond Hill",k:"Middle Eastern",r:4.2},
    {n:"Shinta Japanese",c:"Richmond Hill",k:"Asian",r:4.4},
    {n:"QJD Peking Duck",c:"Richmond Hill",k:"Asian",r:4.3},
    {n:"Mandala Cafe",c:"Richmond Hill",k:"Masla7a",r:4.5},
    {n:"Cyan Cafe",c:"Richmond Hill",k:"Masla7a",r:4.2},
    {n:"Mado",c:"Richmond Hill",k:"Turkish",r:4.2},
    {n:"Mi-Ne Sushi",c:"Richmond Hill",k:"Sushi",r:4.3},
    {n:"Bar Burrito",c:"Richmond Hill",k:"Mexican",r:4.0},
    {n:"Chreston",c:"Richmond Hill",k:"Italian",r:4.2},
    {n:"Aneal's",c:"Richmond Hill",k:"Caribbean",r:4.4},
    {n:"Restoran Malaysia",c:"Richmond Hill",k:"Asian",r:4.3},
    {n:"Toppings",c:"Richmond Hill",k:"Burgers",r:4.2},
    {n:"Bamiyan Kabob",c:"Richmond Hill",k:"Middle Eastern",r:4.2},
    {n:"Big Trio Wonton",c:"Richmond Hill",k:"Asian",r:4.3},
    {n:"Chillax Coffee",c:"Richmond Hill",k:"Dessert",r:4.4},
    {n:"Tirbeh",c:"Richmond Hill",k:"Middle Eastern",r:4.3},
    {n:"D Spot Dessert",c:"Markham",k:"Dessert",r:4.4},
    {n:"Bamiyan Kabob",c:"Markham",k:"Middle Eastern",r:4.3},
    {n:"Potbelly's",c:"Markham",k:"Egyptian",r:4.3},
    {n:"Pitalicious",c:"Markham",k:"Middle Eastern",r:4.4},
    {n:"Barakas",c:"Markham",k:"Middle Eastern",r:4.3},
    {n:"Pitaland",c:"Markham",k:"Middle Eastern",r:4.2},
    {n:"Kinton Ramen",c:"Markham",k:"Asian",r:4.4},

    // ================= AURORA =================
    {n:"Pita Golden Pocket",c:"Aurora",k:"Middle Eastern",r:4.8},
    {n:"Gladiator Burger",c:"Aurora",k:"Burgers",r:4.5},
    {n:"Bamiyan Kabob",c:"Aurora",k:"Middle Eastern",r:4.3},
    {n:"Mary Brown's",c:"Aurora",k:"Burgers",r:4.4},
    {n:"Minami Sushi",c:"Aurora",k:"Sushi",r:4.4},
    {n:"Fishbone Kitchen",c:"Aurora",k:"Sushi",r:4.5},
    {n:"Shawarma Land",c:"Aurora",k:"Middle Eastern",r:4.2},
    {n:"Bombay's Chutney",c:"Aurora",k:"Pakistani",r:4.1},
    {n:"Kibo Sushi",c:"Aurora",k:"Sushi",r:4.3},
    {n:"Hero Certified",c:"Aurora",k:"Burgers",r:4.1},
    {n:"Wimpy's Diner",c:"Aurora",k:"Burgers",r:4.0},
    {n:"Swiss Chalet",c:"Aurora",k:"Burgers",r:4.0},
    {n:"Locale",c:"Aurora",k:"Italian",r:4.3},
    {n:"Symposium Cafe",c:"Aurora",k:"Dessert",r:4.2},

    // ================= AJAX / PICKERING / MILTON / OAKVILLE =================
    {n:"D Spot Dessert",c:"Ajax",k:"Dessert",r:4.3},
    {n:"Karachi Xpress",c:"Ajax",k:"Pakistani",r:4.0},
    {n:"Affy's Premium",c:"Ajax",k:"Steakhouse",r:4.2},
    {n:"Shamrock",c:"Ajax",k:"Burgers",r:4.3},
    {n:"Pizzaville",c:"Ajax",k:"Italian",r:4.1},
    {n:"Pizza Pizza",c:"Ajax",k:"Italian",r:3.8},
    {n:"Kelsey's",c:"Ajax",k:"Burgers",r:4.0},
    {n:"Chuck's Roadhouse",c:"Ajax",k:"Steakhouse",r:3.9},
    {n:"Mount Zion",c:"Pickering",k:"Caribbean",r:4.4},
    {n:"Big M Burgers",c:"Pickering",k:"Burgers",r:4.3},
    {n:"Yardies",c:"Pickering",k:"Caribbean",r:4.2},
    {n:"Malt N Salt",c:"Milton",k:"Burgers",r:4.6},
    {n:"Marquee Steak",c:"Milton",k:"Steakhouse",r:4.4},
    {n:"Hakka Wok",c:"Milton",k:"Asian",r:4.2},
    {n:"Adonis",c:"Oakville",k:"Middle Eastern",r:4.3},
    {n:"Chef's Door",c:"Oakville",k:"Middle Eastern",r:4.2},
    {n:"Monaghan's",c:"Oakville",k:"Burgers",r:4.1},
    {n:"Sultan's",c:"Oakville",k:"Turkish",r:4.4},
    {n:"Gladiator Burger",c:"Oakville",k:"Burgers",r:4.5},
    {n:"Kibo Sushi",c:"Oakville",k:"Sushi",r:4.3}
];